# Generated by Django 4.0.3 on 2022-04-02 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_details', models.TextField()),
                ('full_detail', models.TextField(blank=True, null=True)),
                ('inside_box', models.TextField(default=None)),
                ('price', models.CharField(max_length=10)),
                ('image', models.URLField(blank=True, max_length=2048, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('review_rating', models.CharField(blank=True, default=None, max_length=20)),
                ('buy_link', models.URLField(blank=True, max_length=2048, null=True)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Games', 'Games'), ('Health', 'Health'), ('Skin', 'Skin'), ('Health', 'Health'), ('Makeup', 'Makeup'), ('Lotions', 'Lotions'), ('Shampoo', 'Shampoo'), ('Food', 'Food')], default='Select category', max_length=100)),
                ('favorite', models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
