# Generated by Django 4.0.3 on 2022-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_details_product_short_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Django', 'Django'), ('Kivy', 'Kivy'), ('Linux', 'Linux'), ('Other', 'Other')], default='Select category', max_length=100),
        ),
    ]
