# Generated by Django 4.0.3 on 2022-04-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Games', 'Games'), ('Health', 'Health'), ('Skin', 'Skin'), ('Health', 'Health'), ('Makeup', 'Makeup'), ('Lotions', 'Lotions'), ('Shampoo', 'Shampoo'), ('Food', 'Food')], default='Select category', max_length=100),
        ),
    ]
