# Generated by Django 4.0.3 on 2022-04-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='product',
            name='review_rating',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
