# Generated by Django 4.0.3 on 2022-04-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_options_product_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_rating',
        ),
    ]
